### ISSUE TITLE
Schaefer100-17Networks

### ISSUE THREAD

**Issue by mohammadakradi** [saratheriver/enigma-extra#1]
Dear @saratheriver 
I was looking for the gene expression dataset based on Schaefer-100 17networks, but the ENIGMA toolbox supports Schaefer-100 "7Netowkrs". I am wondering could you upload the AHBA dataset based on Schaefer-100 with 17networks by any chance?
Best Regards,
Mohammad

**Comment by saratheriver** [comment]
Dear Mohammad,

Our functions currently do not support the 17 network Schaeffer parcellations - This could perhaps be added in an eventual release (after the Christmas break, sometimes in early 2022).

The AHBA gene expression maps are obtained from the amazing abagen toolbox (https://github.com/rmarkello/abagen). They have a very thorough documentation on how to upload your own parcellation and generate the parcellated microarray expression data for your analysis. Check out their documentation here: https://abagen.readthedocs.io/en/stable/#

Hope this helps,

Sara.
