### ISSUE TITLE
NaN in enigma-extra/ahba/allgenes_stable_r0.2.csv

### ISSUE THREAD

**Issue by Dr-Chen-Xiaoyu** [saratheriver/enigma-extra#2]
Hi, [saratheriver](https://github.com/saratheriver)

When I am using fetch_ahba() from enigmatoolbox to fetch gene expression data of allgenes_stable_r0.2.csv, I find that two brain regions' data are all NaNs. The situation is shown below:

```
label | A1BG
...
R_superiortemporal | 0.642762
R_supramarginal | 0.407603
R_frontalpole | NaN
R_temporalpole | NaN
R_transversetemporal | 0.510042
R_insula | 0.645202
...
```

Are these NaNs are just what it is ？ or I missed something ?

Best,
Xiaoyu

**Comment by saratheriver** [comment]
Hello,

This is normal; these regions were not matched to any tissue samples most likely due to the fact that only two of the six donors have tissue samples taken from the right hemisphere.


Sara.

**Comment by Dr-Chen-Xiaoyu** [comment]
Thanks 😊
